const data = {
    products: [
        {
            _id: '1',
            name: 'Jeans Shirt Ivy Park',
            category: 'Shirt',
            image: '/images/p1.jpg',
            price: 120,
            brand: 'RODEO',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Jeans Pants Ivy Park',
            category: 'Pants',
            image: '/images/p2.jpg',
            price: 120,
            brand: 'RODEO',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Jeans Sweatshirt Ivy Park',
            category: 'Sweatshirt',
            image: '/images/p3.jpg',
            price: 150,
            brand: 'RODEO',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Jeans Body Ivy Park',
            category: 'Body',
            image: '/images/p4.jpg',
            price: 70,
            brand: 'RODEO',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'Jeans Overalls Ivy Park',
            category: 'Overalls',
            image: '/images/p5.jpg',
            price: 200,
            brand: 'RODEO',
            rating: 3.5,
            numReviews: 10,
            description: 'high quality product',
        },
    ],
};

export default data

